# Generated by Django 4.0.3 on 2022-08-09 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('sprint', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('p', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=100)),
                ('issueid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.issue')),
                ('userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200)),
                ('issue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.issue')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iss', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.issue')),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
    ]
